import 'package:flutter/material.dart';
import '../../constants/app_colors.dart';

class AdminLiveAdsScreen extends StatelessWidget {
  const AdminLiveAdsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    // TODO: replace with real data from Firestore (collection: advertisements, status: live).
    // "revenue" here = poll-reply revenue generated by this ad so far
    // (poll responses × per-reply cost, per Blueprint Chapter 6).
    final List<Map<String, String>> liveAds = [
      {'title': 'न्यू फॅशन पॉइंट — Video Ad', 'by': 'CP — पुणे जिल्हा', 'type': 'Video', 'responses': '340', 'revenue': '₹170.00'},
      {'title': 'भोसरी जनरल स्टोअर्स — Photo Ad', 'by': 'Franchise — भोसरी', 'type': 'Photo', 'responses': '512', 'revenue': '₹128.00'},
      {'title': 'दिवाळी सेल — संपूर्ण जिल्हा', 'by': 'CP — पुणे जिल्हा', 'type': 'Text', 'responses': '890', 'revenue': '₹89.00'},
    ];
    final totalRevenue = liveAds.fold<double>(
      0,
      (sum, ad) => sum + double.parse(ad['revenue']!.replaceAll('₹', '').replaceAll(',', '')),
    );

    return Scaffold(
      backgroundColor: AppColors.lightGrey,
      appBar: AppBar(
        backgroundColor: AppColors.primaryBlue,
        foregroundColor: Colors.white,
        title: const Text('Live जाहिराती (संपूर्ण नेटवर्क)'),
      ),
      body: Column(
        children: [
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(16),
            color: Colors.white,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                Column(children: [
                  Text('${liveAds.length}', style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppColors.primaryBlue)),
                  const Text('Live जाहिराती', style: TextStyle(fontSize: 12, color: AppColors.textLight)),
                ]),
                Column(children: [
                  Text('₹${totalRevenue.toStringAsFixed(2)}', style: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: AppColors.successGreen)),
                  const Text('एकूण जमा झालेला Revenue', style: TextStyle(fontSize: 12, color: AppColors.textLight)),
                ]),
              ],
            ),
          ),
          Expanded(
            child: ListView.separated(
              padding: const EdgeInsets.all(16),
              itemCount: liveAds.length,
              separatorBuilder: (_, __) => const SizedBox(height: 10),
              itemBuilder: (ctx, i) {
                final ad = liveAds[i];
                return Container(
                  padding: const EdgeInsets.all(14),
                  decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(14), border: Border.all(color: Colors.grey.shade200)),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(children: [
                        const Icon(Icons.campaign_outlined, color: AppColors.primaryBlue),
                        const SizedBox(width: 10),
                        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                          Text(ad['title']!, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: AppColors.textDark)),
                          Text('${ad['by']} • ${ad['type']} Ad', style: const TextStyle(fontSize: 12, color: AppColors.textLight)),
                        ])),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                          decoration: BoxDecoration(color: AppColors.successGreen.withValues(alpha: 0.12), borderRadius: BorderRadius.circular(20)),
                          child: const Text('Live', style: TextStyle(color: AppColors.successGreen, fontSize: 11, fontWeight: FontWeight.w600)),
                        ),
                      ]),
                      const Divider(height: 20),
                      Row(children: [
                        const Icon(Icons.forum_outlined, size: 14, color: AppColors.textLight),
                        const SizedBox(width: 4),
                        Text('${ad['responses']} Poll Responses', style: const TextStyle(fontSize: 12, color: AppColors.textDark)),
                        const Spacer(),
                        Text('जमा: ${ad['revenue']}', style: const TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.successGreen)),
                      ]),
                    ],
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
